### ISSUE TITLE
js文件不存在, 出现 Oops, an error occurred!

### ISSUE THREAD

**Issue by marswang** [oaistatic/oaistatic.github.io#1]
https://oaistatic-cdn.closeai.biz/_next/static/chunks/4114.f0c19e9fbc4a2762.js?dpl=37f91bfd782f6b4fb81dd5cd885a42d5d31cc4a3
文件不存在
<img width="1718" alt="image" src="https://github.com/oaistatic/oaistatic.github.io/assets/3132466/7c1d4463-ebbf-49a0-ae3b-6481e2b34e0b">

**Comment by gcslaoli** [comment]
fixed
